### ISSUE TITLE
"pi_per" stat (Puissance pièges)

### ISSUE THREAD

**Issue by KiwiJaune** [pboutin/dofus-data#10]
The "pi_per" stat is not correctly parsed.

Example :

"8092-dagues-bouwin": {"name": "Les Dagues du Bouwin", "level": "134", "recipe": {"13733-boulier-zoth": "28", "12733-substrat-foret": "1", "15067-patte-gruche": "10", "13061-galet-boucane": "3", "2621-barbe-chouque": "9", "7035-pyrute": "2", "1680-corne-brulee-minotoror": "1", "7283-peau-tanukoui-san": "9"}, "link": "http://www.dofus.com/fr/mmorpg/encyclopedie/armes/8092-dagues-bouwin", "effects": ["fo", 50, "vi", 250, "do", 10, **"pui", 20**, "agi", 30, "re_neutre", 10, "re_air", 10, **"pui", 10**], "type": "Dague"}

Proposition :
Modification in DofusData.py
'pui': u'\d Puissance',
to
'pui': u'\d Puissance$',

(Not tested)

**Comment by pboutin** [comment]
I will also test this one.

**Comment by pboutin** [comment]
Fixed
