### ISSUE TITLE
Incomplete stat for crit on spells

### ISSUE THREAD

**Issue by KiwiJaune** [pboutin/dofus-data#11]
It seems that a "X % crit on spell Y" stat is indicated as simple "cri" stat in the dofus-data.json file.

Exemple : 

"8659-sangle-huee": {"name": "Sangle Hu\u00e9e", "level": "130", "recipe": {"8770-ecorce-tynril": "1", "8784-talon-achille-abrakleur-sombre": "2", "8779-carpelle-brouture": "18", "8782-bractee-chiendent": "30", "2651-ver-feu": "1", "8781-calice-fecorce": "24", "8778-etamine-floribonde": "20", "8780-sepale-nerbe": "28"}, "link": "http://www.dofus.com/fr/mmorpg/encyclopedie/equipements/8659-sangle-huee", "effects": [**"cri", 20, "cri", 25**, "Augmente la port\u00e9e du sort Souillure de 1", "Augmente la port\u00e9e du sort Chamrak de 1"], "type": "Ceinture"},

Original stats :
20% Critique sur le sort Ethylo
25% Critique sur le sort Vague à Lame
Augmente la portée du sort Souillure de 1
Augmente la portée du sort Chamrak de 1

Proposition :
Modification in DofusData.py
'cri': u'\d\% Critique',
to
'cri': u'\d\% Critique$',

(Not tested)

**Comment by pboutin** [comment]
Will try your regex, will keep you posted.

**Comment by pboutin** [comment]
Fixed
