### ISSUE TITLE
"do_ren" stat (Renvoi dommage)

### ISSUE THREAD

**Issue by KiwiJaune** [pboutin/dofus-data#12]
The "do_ren" stat is not correctly red.

Exemple :

"6988-sulik": {"name": "Sulik", "level": "167", "recipe": {"6441-poils-moon": "10", "7305-etoffe-soryo-firefoux": "2", "7382-etoffe-fantome-leopardo": "2", "7308-etoffe-pandule": "4", "7306-etoffe-yokai-firefoux": "2", "7304-etoffe-maho-firefoux": "2", "7393-etoffe-fantome-pandore": "1", "7307-etoffe-pandore": "6"}, "link": "http://www.dofus.com/fr/mmorpg/encyclopedie/equipements/6988-sulik", "effects": ["vi", 400, "sa", 50, **"Renvoie 11 \u00e0 25 dommages"**, "cha", 60], "type": "Chapeau"}

**Comment by pboutin** [comment]
I will update the regex so it should be parsed correctly, thanks for the report.
